### ISSUE TITLE
Use variable in independant file for request body

### ISSUE THREAD

**Issue by boboz2** [Huachao/vscode-restclient#614] opened 2020-06-17 17:33 UTC
I want to use file path for a request body, and in this file i want to use variable.

This one works (variable in request body)
```
### POST 
@name = toto
POST http://localhost/patient HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "{{name}}"
}
```

This one works (file path for request body)
```
### POST 
@name = toto
POST http://localhost/patient HTTP/1.1
Accept: application/json
Content-Type: application/json

< ./body.json
```

body.json
```
{
    "name": "toto"
}
```

but this one don't works (variable in file path for request body)
```
### POST 
@name = toto
POST http://localhost/patient HTTP/1.1
Accept: application/json
Content-Type: application/json

< ./body.json
```

body.json
```
{
    "name": "{{name}}"
}
```

Thanks

**Comment by Huachao** [comment] 2020-06-18 01:25
@boboz2 this is by design, 
Duplicate of #427

**Closed by Huachao** 2020-06-18 01:25 UTC
