### ISSUE TITLE
call requests in sequence

### ISSUE THREAD

**Issue by vit100** [Huachao/vscode-restclient#356] opened 2019-04-12 18:36 UTC
Would be nice to call all requests in file in sequence automatically.
For example
1 get token
2 get resource (with token retrieved in step1)

**Comment by DaveJohnson8080** [comment] 2019-06-07 02:39
This looks similar to #364 that was marked as an enhancement. 

This would be the Postman killer in my book.

**Comment by Huachao** [comment] 2019-06-10 03:19
@vit100 @DaveJohnson8080 @JJB-123 Duplicate of #364, close this to in favor of that

**Closed** 2019-06-10 03:19 UTC
