### ISSUE TITLE
Negotiate support

### ISSUE THREAD

**Issue by weq** [Huachao/vscode-restclient#413] opened 2019-09-02 13:56 UTC
Any plans to support this? We use a lot of apis that support Negotiate and it would be a smother experience to use that instead of Basic.

**Comment by Huachao** [comment] 2019-09-02 14:54
what do you mean negotiate here, could you pls provide more details?

**Comment by weq** [comment] 2019-09-02 14:56
Oh I'm sorry. Authentication method.
https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/understanding-http-authentication for reference.

**Comment by Huachao** [comment] 2019-09-02 15:11
I found following description in the link you provided

> Negotiate authentication automatically selects between the Kerberos protocol and NTLM authentication, depending on availability. The Kerberos protocol is used if it is available; otherwise, NTLM is tried.

However none of the above.authentication method is supported

**Comment by weq** [comment] 2019-09-03 12:24
I get that there is no support for them as of now. But any plans to implement either? There are plenty of APIs around the world within businesses that utilize either Kerberos or NTLM with negotiation.

**Comment by Huachao** [comment] 2019-09-05 05:02
@weq we have an issue to track the NTLM issue (#15), however, since the underlying `request` library entered into a maintenance mode, so I'd like to implement this after migrating to another http client library. And I'd like to close this to in favor of that one

**Comment by Huachao** [comment] 2019-09-05 05:02
Duplicate of #15

**Closed by Huachao** 2019-09-05 05:02 UTC
