### ISSUE TITLE
How to capture multiple elements?

### ISSUE THREAD

**Issue by rdhar** [Huachao/vscode-restclient#605] opened 2020-06-11 15:47 UTC
Hi there,

First off, great work on this amazing extension; it's ideal for quickly pinging endpoints with minimal overhead!

I'm trying to capture multiple elements returned in the response array using this example.

```http
# @name read_comments
GET https://jsonplaceholder.cypress.io/comments?postId=1

@emails = {{read_comments.response.body.$[*].email}}
```

```json
[
  {
    "postId": 1,
    "id": 1,
    "name": "id labore ex et quam laborum",
    "email": "Eliseo@gardner.biz",
    "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
  },
  {
    "postId": 1,
    "id": 2,
    "name": "quo vero reiciendis velit similique earum",
    "email": "Jayne_Kuhic@sydney.com",
    "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
  }
]
```

However, `read_comments.response.body.$[*].email` only returns the first instance it finds despite using the `*` wildcard. Is there another way to capture multiple elements and [return an array of results](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html#multiple)?

**Comment by Huachao** [comment] 2020-06-12 01:19
Duplicate of #197

**Closed by Huachao** 2020-06-12 01:19 UTC
