### ISSUE TITLE
Variables in payload file

### ISSUE THREAD

**Issue by ricmrodrigues** [Huachao/vscode-restclient#630] opened 2020-06-30 14:01 UTC
Hi!
Tried to use variables in a file but it didn't work, is this just not supported?
If so, can you point me in the right direction where this logic happens so I can try to make it work and put a PR in?
Thanks!

**Comment by Huachao** [comment] 2020-07-01 01:17
Duplicate of #427 
Close this in favor of #442

**Closed by Huachao** 2020-07-01 01:17 UTC
