### ISSUE TITLE
Client doesn't resend Authorization Header after Location redirects

### ISSUE THREAD

**Issue by JCloudYu** [Huachao/vscode-restclient#68] opened 2017-02-02 17:09 UTC
- VSCode Version: 1.8.3
- OS Version: MacOSX 10.12.3 ( sierra )
- REST Client Version: 0.12.1

Steps to Reproduce:

1. Create two PHP hosts A and B. Both server accepts Authorization Header. When A receives request it will issue a 302 Found Location redirect to B
2. Request A with Authorization Header and the client will not send the header to B.

I've tested the redirection using curl and postman(chrome app), and the authorization header is successfully sent to B.

**Comment by Huachao** [comment] 2017-02-03 01:22
@JCloudYu, since my tool depends on the request package, which has this issue request/request#2527 for now, I will keep eyes on this and to see if we can have any work arounds

**Comment by Huachao** [comment] 2017-07-12 09:02
@JCloudYu I can't repro your issue as you described in both curl and postman. I'd like to close it and mark it as not reproducible. Please feel free yo reopen it if you have any concern

**Closed by Huachao** 2017-07-12 09:02 UTC
Labels: upstream
