### ISSUE TITLE
Include other files

### ISSUE THREAD

**Issue by asmith3006** [Huachao/vscode-restclient#371] opened 2019-06-05 21:41 UTC
Alternatively to https://github.com/Huachao/vscode-restclient/issues/370 

It would be really cool to be able to include other files in a file.

Scenario: I'm making an API with lots of methods in there (Parcels, Customers, Orders etc.). It would be great to be able to have:

BaseConfig.http
Parcel.http
Customer.http
Order.http

Then BaseConfig.http can contain things like the URL and the method for getting the session / authentication processes complete and then the Parcel.http file can contain

```@include BaseConfig.http```

Or similar, to get access to those variables.

**Comment by Huachao** [comment] 2019-10-14 02:12
Duplicate of #182

**Comment by Huachao** [comment] 2019-10-14 02:12
@asmith3006 close this to favor of that one.

**Closed by Huachao** 2019-10-14 02:12 UTC
