### ISSUE TITLE
Store received cookies in variables to be used in subsequent request

### ISSUE THREAD

**Issue by nour-s** [Huachao/vscode-restclient#527] opened 2020-02-23 17:54 UTC
I have a scenario where I receive an XSRF token in a cookie, but it should be used as a header in the next request, so I was thinking to make it possible to do something like:

`@token = {{requestName.response.cookies['XSRF-Token']}}`

**Comment by Huachao** [comment] 2020-02-24 04:10
Duplicate of #316

**Closed by Huachao** 2020-02-24 04:10 UTC
