### ISSUE TITLE
Icons showing up twice in response preview

### ISSUE THREAD

**Issue by tgnanakumar** [Huachao/vscode-restclient#778] opened 2021-02-19 18:48 UTC
- REST Client Version: 0.24.4
- VSCode Version: 1.53.2
- OS Version: Windows 10

Response preview is showing up icons twice at the right side top before More Actions (...) menu for each of the following options,
- Save Full Response
- Save Response Body
- Copy Response Body

Please find below screenshot for the same,
![Options](https://user-images.githubusercontent.com/29971063/108547810-424aa000-72eb-11eb-8a80-37b91060b24e.jpg)

**Comment by ToMakeSense** [comment] 2021-07-13 03:18
Same situation here

REST Client Version: 0.24.5
VSCode Version: 1.57.1
OS Version: Windows 10

**Comment by ToMakeSense** [comment] 2021-12-09 08:32
The issue disappeared itself after the latest release `v0.24.6` 
```
Version: 1.62.3 (system setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by ToMakeSense** [comment] 2021-12-09 08:33
similar issue #887

**Comment by Huachao** [comment] 2021-12-10 03:29
Duplicate of #887

**Closed by Huachao** 2021-12-10 03:29 UTC
