### ISSUE TITLE
Unexpected end-of-input: expected close marker for ARRAY

### ISSUE THREAD

**Issue by akefirad** [Huachao/vscode-restclient#185] opened 2018-04-10 12:08 UTC
- VSCode Version: 1.22.1
- OS Version: Ubuntu 18.04 Beta 2
- REST Client Version: 0.18.1

I've got a request like this:
```json
POST https://example.com/some-rest-endpoint
content-type: application/json

{
   "meta":{
      "location":{
         "countries":[
            "US"
         ],
         "locations":[
             
         ]
      }
   }
}
```
When I send the request I get a 400 response from our restful service (spring+jetty+jackson) due to
```
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for ARRAY (from [Source: java.io.PushbackInputStream@5c5122c; line: 6, column: 10])
 at [Source: java.io.PushbackInputStream@5c5122c; line: 10, column: 184]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:470)
	at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:501)
	at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:509)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2857)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:264)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3708)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2113)
```
But when I remove the white space in the `locations` field, it returns 200 response.
Any help?

**Comment by Huachao** [comment] 2018-04-10 13:46
@akefirad in fact, I have no idea, can you please create an issue in Jackson project to get a better view?

**Comment by akefirad** [comment] 2018-04-11 18:58
@Huachao I'm not sure whether it's completely a Jackson question/issue, since sending exactly the same request (with the same body) via `curl` will gets you 200 response. Is it possible to debug what exactly the client sends as the request body? How? Thanks.

**Comment by Huachao** [comment] 2018-04-11 22:24
@akefirad you are right, it's really an issue from my extension, blank line is not allowed in request body currently.

**Comment by Huachao** [comment] 2018-04-18 13:41
@akefirad since it's by design, I'd like to close the issue. You should not have blank line in plain request body. If you really wish, one way is to put the request body in a file.

**Closed by Huachao** 2018-04-18 13:41 UTC
Labels: as-designed, question
