### ISSUE TITLE
POST doesn't send body to server

### ISSUE THREAD

**Issue by tcodes0** [Huachao/vscode-restclient#789] opened 2021-03-11 22:06 UTC
- REST Client Version: 0.24.4
- VSCode Version: 1.53.2
- OS Version: Linux Arch7 5.11.1-arch1-1 #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000 x86_64 GNU/Linux

Steps to Reproduce:

1. Paste code in a file called `curl.http`. Click send request. Server receives no body. Exact same code from terminal works as expected
```
curl 'http://localhost:3200/v1/verify-dob' \
  -X POST \
  --data-raw '{"dob": "1992-02-14"}' \
  --compressed
```

**Comment by vkristijan** [comment] 2023-05-08 13:02
Looks like a duplicate of #790 which has been fixed in the meantime.
@Huachao could you please close this issue?

**Closed** 2023-05-19 17:21 UTC
