### ISSUE TITLE
Copy (Ctrl+C) not working anymore in the response window

### ISSUE THREAD

**Issue by cassioconti** [Huachao/vscode-restclient#656] opened 2020-08-01 16:01 UTC
- REST Client Version: v0.24.1
- VSCode Version: 1.47.3 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Run a request with REST Client.
2. On the opened response window, select some part of the response and try to copy (Ctrl+C)
3. Try to paste in the editor or another text editor. The selected text was not copied.

This used to work.

**Comment by quammy** [comment] 2020-08-03 11:28
+1
temporary solution - on the top right corner there's a button to copy *all* the text of the response...

**Comment by Huachao** [comment] 2020-08-04 05:41
Duplicate of #641

**Closed by Huachao** 2020-08-04 05:41 UTC
