### ISSUE TITLE
Auth Request prior to REST call

### ISSUE THREAD

**Issue by sgentile** [Huachao/vscode-restclient#665] opened 2020-08-17 13:19 UTC
I'm using graphql , the queries work great.

We have a 3rd party auth call we make to get a bearer token.   I would like to make that request, get the token, and set it in our queries (we were doing this in our postman calls).

Is this possible - a 'pre-script' request to get and then set a {token} variable ?

**Comment by Huachao** [comment] 2020-08-18 04:40
Duplicate of #209

**Closed by Huachao** 2020-08-18 04:40 UTC
