### ISSUE TITLE
HTTP/2 not support

### ISSUE THREAD

**Issue by ZER0-Nu1L** [Huachao/vscode-restclient#813] opened 2021-04-09 04:05 UTC
HTTP/2 not support?
```http
GET http://httpbin.org HTTP/2
```
respond `HTTP/1.1 400 Bad Request`.

**Comment by fschaefer** [comment] 2021-04-09 08:06
Duplicate of #271

**Comment by Huachao** [comment] 2021-07-07 04:44
Duplicate of #271

**Closed by Huachao** 2021-07-07 04:44 UTC
