### ISSUE TITLE
SOCKS5 Proxy Support

### ISSUE THREAD

**Issue by cumminsd** [Huachao/vscode-restclient#982] opened 2022-03-24 16:52 UTC
We have a situation where we use a SOCKS5 proxy for some URLS, but not all. It would be great to have a way to configure a SOCKS proxy server and then have some URLS use it and others not, all within the file. Or at least all URLS is one file uses it and another file doesn't.

**Comment by Huachao** [comment] 2022-06-21 15:46
Duplicate of #194

**Closed by Huachao** 2022-06-21 15:46 UTC
