### ISSUE TITLE
Responses open in new tab despite the setting

### ISSUE THREAD

**Issue by moniuch** [Huachao/vscode-restclient#949] opened 2021-12-28 18:50 UTC
Despite having **Show Response in Different Tab** checked off (cleared), the responses still open in a new tab.
I would like to achieve a "docked" setup where I can repeatedly Send same request and expect the response to refresh in the same, opened tab. A case where it'd help would be testing expiring tokens.

This could be a bug, or this could be seen a feature request to provide a better solution, like maybe an inline response in an expandable div below?

v0.24.6

**Comment by SuzurikawaChihiro** [comment] 2022-01-02 16:30
me too

I used to be able to send requests in succession, but now it's hard to use because I have to move tabs.

**Comment by simplenotezy** [comment] 2022-01-04 21:11
I have the same issue. I didn't configure anything though, but I was surprised of this behaviour

**Comment by willyt150** [comment] 2022-01-05 22:06
I think I'm experiencing the same problem. When I close and re-open vscode it will be fixed for a short period, so I can just keep hitting the send request button and it refreshes the response in the column to the right, but then it randomly stops and starts opening a new full window tab covering up my http code

**Comment by MorganTiley** [comment] 2022-01-06 14:26
@moniuch @SuzurikawaChihiro  @simplenotezy  @willyt150 I have experienced the same but found a workaround (and possibly related to root cause?) - After first request, move response to new split pane, then "lock" the group of tabs with your http file in it. Now no new tabs will open in this group and subsequent requests will go to the new pane:
![image](https://user-images.githubusercontent.com/1864477/148397847-36f24026-0a48-43ef-9dd4-89ff89f7caa2.png)

At least works for now

**Comment by willyt150** [comment] 2022-01-06 18:02
@MorganTiley thank you very much for that workaround. It's working for me as well.

It's annoying having to do it initially each time, but still better than nothing.

**Comment by matiasg77** [comment] 2022-01-06 23:42
I have the same issue!!

**Comment by bartsimp** [comment] 2022-01-07 09:58
same here
@MorganTiley doesn't work for me (VSCode 1.63.2, REST Client v0.24.6)

**Comment by simplenotezy** [comment] 2022-01-07 20:25
@MorganTiley But that will still create tons of new tabs inside that group :/ So it's not ideal.

![image](https://user-images.githubusercontent.com/3786627/148602805-53521129-b829-4f8d-8353-cea237da4b70.png)

**Comment by MorganTiley** [comment] 2022-01-07 20:31
@simplenotezy  make sure this setting for the extension is off:
![image](https://user-images.githubusercontent.com/1864477/148603489-f9ef435d-2631-4e98-97b1-cfae4cd941e6.png)

**Comment by simplenotezy** [comment] 2022-01-07 20:50
@MorganTiley thanks; that will prevent a new tab from opening, but if I resend the request, it will open in the current tab. Even if the request tab is locked.. hmm

**Comment by simplenotezy** [comment] 2022-01-07 20:51
So far, the best results i get if I have "show response in different tab" cheked, and then I don't need to lock groups. But new tabs will open, but they can be closed later on I guess..

**Comment by willyt150** [comment] 2022-01-07 23:08
@simplenotezy so the first time I tried to follow @MorganTiley 's steps I misread and locked the wrong group.

So the steps I've found to work are (this is assuming the "Show Response in Different Tab" option is unchecked):
1. Send the first request, which properly opens up the 2nd column (split view)
2. Choose "Lock Group" for the 1st column (where my .http file is and where I sent the request from)
![image](https://user-images.githubusercontent.com/1190775/148618513-0f7897da-5b07-4677-a456-24acdf7a1544.png)

From that point forward, I can repeatedly send requests and it's replacing the single response tab in the 2nd column.

When locked the column containing the response, the 2nd time I sent a request the response view took over the whole view.

**Comment by simplenotezy** [comment] 2022-01-07 23:50
Ahh! I see. I'll try that workaround

**Comment by simplenotezy** [comment] 2022-01-07 23:51
That worked! Thanks

**Comment by ckonrado** [comment] 2022-01-28 10:26
Wow - this is really annoying. It used to work perfectly, but seems to have changed by itself?

**Comment by Huachao** [comment] 2022-02-07 06:24
@moniuch @SuzurikawaChihiro @simplenotezy @willyt150 @MorganTiley @ckonrado @bartsimp this should be fixed after VS Code upgrades to the latest version 1.64

**Closed by Huachao** 2022-02-07 06:24 UTC
