### ISSUE TITLE
Extension hosts randomly fails when rest client extension enabled

### ISSUE THREAD

**Issue by defectus** [Huachao/vscode-restclient#198] opened 2018-04-25 11:18 UTC
- VSCode Version: 1.22.2 (1.22.2)
- OS Version: MacOS 10.13.4 (17E199)
- REST Client Version: 0.18.3

Steps to Reproduce:

1. enable the rest client extension 
2. try to work for some time
3. extension host crashes and js console shows a weird rest client error.

``` 
Extension host terminated unexpectedly.
e.onDidNotificationChange @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2217
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2775 [Extension Host] debugger inspector at %c/Users/defectus/.vscode/extensions/humao.rest-client-0.18.3/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:33
                        throw error;
                        ^

Error: write EPIPE
	at exports._errnoException (util.js:1050:11)
	at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)
```

**Comment by Huachao** [comment] 2018-04-25 12:28
@defectus it seems the application insights rethrow an exception, did you meet this in previous versions? And I have disabled the exception collection of application insights, will publish a new version tomorrow. Do you have other interesting things to share for this crash?

**Comment by Huachao** [comment] 2018-04-25 12:58
@defectus The error seems related to the uncaught exception in the process, in other words, there should be other root cause for the crash. From the error type EPIPE, it seems piping to a closed stream. Anyway I would like to disable this behavior that rethrow uncaught exception.

**Comment by defectus** [comment] 2018-04-26 05:28
I agree that this issue may be very hard to debug - it happens intermittently and is probably not coming from your code (guessing by the `applicationinsights` module).
I'll try to get more information although that may be difficult as the problem occurs once or twice a day.

**Comment by Huachao** [comment] 2018-05-10 07:33
@defectus do you still meet this since version 0.18.4?

**Comment by defectus** [comment] 2018-05-10 07:44
Yes, on my Mac. Strangly it's OK on my Ubuntu.
Let me reiterate, that disabling the rest client makes the errors go away. The moment I enable the plugin I start getting the errors.
Also, I'm not sure whether that's something specific to my installation or if it affects other people.

**Comment by Huachao** [comment] 2018-05-10 07:48
@defectus can you make sure the version on your macOS is 0.18.4? And you can use `Reinstall Extension...` command of vscode to ensure reinstall it.

**Comment by Huachao** [comment] 2018-06-11 02:59
@defectus I'd like to close the issue now since no one else reported this issue, and you can reopen it as you wish.

**Closed by Huachao** 2018-06-11 02:59 UTC
Labels: bug

**Comment by defectus** [comment] 2018-06-11 06:39
Thanks for that, I no longer have access to a Mac and the issue seems to be excelusiveto Mac.
