### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dc-avasilev** [Huachao/vscode-restclient#495] opened 2020-01-24 10:00 UTC
- Issue Type: `Performance`
- Extension Name: `rest-client`
- Extension Version: `0.23.1`
- OS Version: `Darwin x64 19.2.0`
- VSCode version: `1.41.1`
[humao.rest-client-unresponsive.cpuprofile.txt](https://pastebin.com/04FezN1L)

**Comment by Huachao** [comment] 2020-03-03 15:19
@dc-avasilev how many requests stored in your `.http` file and how often do you meet this problem,

**Comment by dc-avasilev** [comment] 2020-03-05 09:36
> @dc-avasilev I have several questions for you:
> 
> 1. How many requests stored in your `.http` file?
> 2. How often do you meet this problem?
> 3. How do you fix this issue in this situation?
> 
> Thanks in advance.

1. ~10
2. 1 time, in last two weeks, not often
3. idk, im QA not a programmer :)

**Comment by Huachao** [comment] 2020-03-09 06:42
Duplicate of #463

**Closed by Huachao** 2020-03-09 06:42 UTC
Labels: performance
