### ISSUE TITLE
Debugging not working when sending request

### ISSUE THREAD

**Issue by tonilxm** [Huachao/vscode-restclient#398] opened 2019-07-31 02:29 UTC
- VSCode Version:1.36.1
- OS Version: Mac High Sierra
- REST Client Version: 0.21.3

Steps to Reproduce:

1. Open VSCode 
2. Set Breakpoint on PHP Script
3. Run PHP Debug
4. Run 'Send Request'
5. Breakpoint not reached
6. Try using Postman, debugging works as expected, breakpoint reached.

I am not sure if i need to put this into 'Bug' or 'Feature' but i am working on microservices project and having this 'bug' is a HUGE miss for me and my team. I hope you can address this quickly coz this ext rocks!

![WeChatGoPnpRequest_http_—_pccw_oocl_mid](https://user-images.githubusercontent.com/4486196/62180660-11a6bc80-b37b-11e9-9a03-b396cbe35311.png)

![ItemController_php_—_pccw_oocl_mid](https://user-images.githubusercontent.com/4486196/62179108-8bd44280-b375-11e9-825f-6bbe0a664c61.png)

![ItemController POSTMAN _php_—_pccw_oocl_mid](https://user-images.githubusercontent.com/4486196/62179094-7e1ebd00-b375-11e9-9144-98522df63ca3.png)

**Comment by Huachao** [comment] 2019-07-31 09:19
@tonilxm it seems that you have an extra `/` in the url, it should be `{{base_url}}/catalog_product/secureTest`

**Comment by tonilxm** [comment] 2019-08-01 05:05
@Huachao : fix and retry but still no luck. Break point still not reached (Postman works as expected). I hope you fix it. Thanks.

**Comment by Huachao** [comment] 2019-08-01 05:07
@tonilxm can you show me the snapshots of both Postman and my extension of the issuing request?

**Comment by tonilxm** [comment] 2019-08-01 08:06
![Response_46ms__—_pccw_oocl_mid](https://user-images.githubusercontent.com/4486196/62276285-ea7ce780-b46d-11e9-8f01-54dc0f6263f8.png)
![Screen Shot 2019-08-01 at 15 04 03](https://user-images.githubusercontent.com/4486196/62276290-ecdf4180-b46d-11e9-9d7b-bc5878c4a278.png)
![Postman](https://user-images.githubusercontent.com/4486196/62276296-efda3200-b46d-11e9-97ed-729917a6f97b.png)

**Comment by Huachao** [comment] 2019-08-01 08:26
@tonilxm what are the collapsed temporary request headers in *Postman* ?

**Comment by tonilxm** [comment] 2019-08-02 02:22
<img width="868" alt="Screen Shot 2019-08-02 at 09 21 36" src="https://user-images.githubusercontent.com/4486196/62339653-f8327b80-b506-11e9-8d3b-7d28694f2894.png">

**Comment by Huachao** [comment] 2019-08-02 02:30
@tonilxm try to add the header in your request of my extension like:
```http
GET {{base_url}}/catalog_product/secureTest

**Comment by tonilxm** [comment] 2019-08-02 03:59
Tried and still not reach breakpoint.

**Comment by Huachao** [comment] 2019-08-02 04:03
@tonilxm Since with my extension, the response body already returns a JSON payload with {"code": 0, "msg": "success"}. Can you check does any other places will return this besides your action code, like the middleware, or something?

**Comment by tonilxm** [comment] 2019-08-02 04:12
![ItemController_php_—_pccw_oocl_mid_and_Postman_Console_and_Postman_and_Debugging_not_working_when_sending_request_·_Issue__398_·_Huachao_vscode-restclient](https://user-images.githubusercontent.com/4486196/62343953-5155db80-b516-11e9-8975-e97e4e68a7c5.png)
![Postman_Console_and_ItemController_php_—_pccw_oocl_mid_and_Postman](https://user-images.githubusercontent.com/4486196/62343954-53b83580-b516-11e9-90d5-6d19c23c038c.png)

**Comment by tonilxm** [comment] 2019-08-02 04:15
I use 'secureTest' endpoint, just for checking. It returns JSON in response body as shown in Postman IDE.

**Comment by Huachao** [comment] 2019-08-02 04:22
@tonilxm I think the first step is to consolidate the request in Postman and my extension, add the `Accept` and `Content-Type` headers in the request. After that check the response. If still not hit, can you update the `code` in your response like changing from `0` to `1`, and re-send the request in my extension again, and check the response.

**Comment by tonilxm** [comment] 2019-08-02 04:50
I have changed response content and added request headers but still not working. Any suggestion?
![Screen Shot 2019-08-02 at 11 49 10](https://user-images.githubusercontent.com/4486196/62345234-b829c380-b51b-11e9-8f11-26132965f1ab.png)

**Comment by Huachao** [comment] 2019-08-02 05:38
@tonilxm from the response body, I think the request sent from my extension actually reaches your  PHP code, the problem is just why the breakpoint doesn't hit? How about open the `.http` file in another VSCode window, and then **debug** your PHP project. Finally, send the request in the newly opened VSCode window?

**Comment by tonilxm** [comment] 2019-08-03 02:19
Still not working. And opening 2 windows fo debugging beat the purpose of using ide. my 2 cents.

![Response_31ms__and_ItemController_php_—_pccw_oocl_mid](https://user-images.githubusercontent.com/4486196/62406068-91c56000-b5cf-11e9-9cbe-c71c7e24317c.png)

**Comment by Huachao** [comment] 2019-08-05 08:27
@tonilxm I have no ideas now, I can only infer that the request sent from the extension already arrived at your server and received the correct response.

**Comment by Huachao** [comment] 2019-11-25 05:03
@tonilxm Did you still meet this issue, if not I'd like to close it since no one else is reporting this bug?

**Comment by Huachao** [comment] 2019-12-02 07:54
@tonilxm since you are no longer reporting this issue since I'd like to close it now. Please feel free to reopen it.

**Closed by Huachao** 2019-12-02 07:54 UTC
Labels: question

**Comment by piperubio** [comment] 2024-04-03 15:50
I was able to successfully run the PHP debugger with REST client by adding the options listed in the following link to the request:

[xDebug Docs Manual Init](https://xdebug.org/docs/step_debug#manual-init)

Here are some code examples that you can add as examples:

```
GET http://localhost/api/hello?XDEBUG_SESSION=my_debug_session 
Accept : Application/json
```

```
GET http://localhost/api/hello
Accept : Application/json 
Cookie: XDEBUG_SESSION=start
```

By adding these options, I was able to set breakpoints and step through my code line by line.

I hope this helps others who are trying to debug their PHP code with REST client.
