### ISSUE TITLE
Post Request Body: Form data does not seem to pipe the contents of XML file

### ISSUE THREAD

**Issue by wboyle-erwin** [Huachao/vscode-restclient#110] opened 2017-08-07 16:17 UTC
- VSCode Version:  1.14.2
- OS Version: Windows 10 1703 15063.502
- REST Client Version: 0.15.1

Steps to Reproduce:

Using the steps provided by the example
POST http://api.example.com/userupload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file[0]"; filename="sample.xml"
Content-Type: application/xml

< C:\sample.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--

The actual content of the xml file sent is "< C:\sample.xml".  It is not getting evaluated and the contents of the file are not piped in instead.

**Comment by Huachao** [comment] 2017-08-08 00:53
@wboyle-erwin I can't reproduce this in my env, and does this file `C:\sample.xml` really exists in your system? You can verify this by `Ctrl+Click` the file name in editor, if exists, it will open the file in a new tab

**Comment by wboyle-erwin** [comment] 2017-08-08 12:59
sample.xml is just a sample statement. the actual file is different that i am trying to use. however, ctrl + click actually does nothing in my environment. the keybinding do not look to be defined.

**Comment by wboyle-erwin** [comment] 2017-08-08 14:11
was able to get ctrl + click enabled by enabling http mode with ctrl k, then m. Currently trying to figure out why it states "Unable to open 'xml file name': resource is not available" even though the location has the file.

**Comment by wboyle-erwin** [comment] 2017-08-08 14:19
making a path similar to file:///C:/sample.xml makes the ctrl+click resolve but still doesn't work

**Comment by Huachao** [comment] 2017-08-08 22:53
are there any special characters in the xml file path

**Comment by Huachao** [comment] 2017-08-10 21:59
@wboyle-erwin could you please help to test the work around mentioned above?

**Comment by wboyle-erwin** [comment] 2017-08-11 15:55
Here is a post of the REST client snippet I have tried. Clicking the link below seems to find the file in question. However, I get "failed to open stream: No such file or directory". Which to me seems like this is not sending any of the contents of the file with the request body. 

POST https://dev.myerwin.io/dm/api/erwin-import HTTP/1.1
Authorization: Basic wboyle Testing123
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file[0]"; filename="sample_descriptions.xml"
Content-Type: application/xml

< file:///C:/Users/WilliamBoyle/Documents/sample_descriptions.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--

I have also tried the following:

< C:/Users/WilliamBoyle/Documents/sample_descriptions.xml
< C:\\Users\\WilliamBoyle\\Documents\\sample_descriptions.xml

Same error as above.

**Comment by Huachao** [comment] 2017-08-14 09:46
@wboyle-erwin When you click the link (file:///), can you really open/find the file, in my test (finally on a windows machine), I can't repro your issue(even with no escape), but my code has bug in Ctrl+Click of file links(in non file:/// scheme).

**Comment by wboyle-erwin** [comment] 2017-09-11 12:59
with 0.15.2 

Clicking the following provides an error now:
< file:///C:/Users/WilliamBoyle/Documents/sample_descriptions.xml

Clicking the following works now:

< C:/Users/WilliamBoyle/Documents/sample_descriptions.xml

The end result of Ctrl + Alt + R is the same unfortunately and doesn't pipe the contents of the file into the request body.

**Comment by Huachao** [comment] 2017-09-12 01:49
@wboyle-erwin could you please sent the request to this url `https://requestb.in/190tr451`, and I will check the actual request you sent to server. Sorry for the incovenience

**Comment by wboyle-erwin** [comment] 2017-09-12 12:34
Sure. I sent the request.

**Comment by Huachao** [comment] 2017-09-12 22:43
@wboyle-erwin as you can see [here](https://requestb.in/190tr451?inspect), your sent request seems already contains the xml file content in request body

**Comment by wboyle-erwin** [comment] 2017-09-13 17:48
Inspecting the request body, i am not seeing the ending WebKitFormBoundary. Is there a limit to how much is sent?

**Comment by Huachao** [comment] 2017-09-13 22:44
This site has some limit to display content. And can you check your server side to see if it receives request body?

**Comment by ozh555** [comment] 2018-01-09 08:24
I had the same problem.

**Comment by Huachao** [comment] 2018-01-09 08:26
@ozh555 could you please provide me some details about your OS and sample request, thanks in advance.

**Comment by ozh555** [comment] 2018-01-09 08:32
@Huachao 
os: windows7 64
vsvode: 1.19.1
REST Client Version: 0.16.2
--------------------------------------------------------------------------------

@ip = http://127.0.0.1:8080


###
POST {{ip}}/server/app
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"

{
    "username":"123456"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.xml"
Content-Type: application/xml

< D:\123.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

**Comment by Huachao** [comment] 2018-01-09 08:38
@ozh555 thanks, could you also temporarily set the request url to `https://requestb.in/1lx73751`, and trigger a request, so that I can confirm your sent out request. Sorry for the inconvenience.

**Comment by Huachao** [comment] 2018-01-09 08:43
@ozh555 as you can see [here](https://requestb.in/1lx73751?inspect), sent out request already contains the XML content

**Comment by ozh555** [comment] 2018-01-09 08:53
@Huachao 
Wow! It's true. 
Maybe my server went wrong! But I use Postman can work，I do not know where is wrong。

**Comment by Huachao** [comment] 2018-01-09 08:59
@ozh555 it still can be a bug of my code, could you please show me the error response before yo u dig into your server side code?

**Comment by Huachao** [comment] 2018-01-09 09:23
@ozh555 except different boundaries, once difference I found is the `Content-Type` is different, mine is `application/json` and another is `text/xml`. So will you server work, if you change your request to `text/xml` of the file

```http
@ip = http://127.0.0.1:8080

POST {{ip}}/server/app
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"

{
"username":"123456"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="1.xml"
Content-Type: text/xml

< D:\123.xml
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by ozh555** [comment] 2018-01-09 09:28
@Huachao 
Still can't work.
and vscode had problem:
![image](https://user-images.githubusercontent.com/5276924/34713819-5b940a56-f562-11e7-80f9-835d0d7a113e.png)

**Comment by Huachao** [comment] 2018-01-09 09:30
@ozh555 so the server didn't respond? Can postman still work now? Sorry for bothering you again and again

**Comment by ozh555** [comment] 2018-01-09 09:32
yes, server didn't respond.
postman work all the time.

**Comment by Huachao** [comment] 2018-01-09 09:34
@ozh555 it's really strange, I will inspect this later when I have a Windows environment. One last thing, if you change back to `application/xml`, will the server respond in time? Thanks.

**Comment by ozh555** [comment] 2018-01-09 09:44
It's still the same.

**Comment by Huachao** [comment] 2018-01-09 09:46
@ozh555 what do you mean __same__ here? Does that mean if we revert to `application/xml`, the server can respond but not the expected response? Or since you use my extension, the server always don't return(just hang there)?

**Comment by ozh555** [comment] 2018-01-09 09:51
server always don't return。
and vscode always waiting。

**Comment by Huachao** [comment] 2018-01-11 09:50
@ozh555 what's your server side stack(**language** + **framework**)?

**Comment by ozh555** [comment] 2018-01-11 09:55
Java-springmvc

**Comment by Huachao** [comment] 2018-02-05 14:29
@ozh555 could you please to try again with latest version 0.17.0?

**Comment by Huachao** [comment] 2018-02-08 07:50
@wboyle-erwin does this problem still exists in 0.17.0?

**Comment by Huachao** [comment] 2018-03-14 14:42
@Platzer could you please to try again with latest version 0.17.0?

**Comment by Huachao** [comment] 2018-09-09 04:50
If no one can repro this issue, I'd like to close it now, please feel free to reopen it

**Closed by Huachao** 2018-09-09 04:50 UTC
Labels: bug

**Comment by ozh555** [comment] 2018-10-11 07:05
I think this bug has since been fixed.

**Comment by newbienewbie** [comment] 2019-02-25 03:16
I'm not sure whether I'm encountering the same bug. 

Recently , when I post a file, it waits there , hangs and and never returns . However, if I send a payload in `application/json` format, this extension works as expected.

For example, I post an image as below: 
```
POST https://eastus.api.cognitive.microsoft.com/face/v1.0/detect?returnFaceLandmarks=true&returnFaceAttributes=age,gender HTTP/1.1
Ocp-Apim-Subscription-Key: xxxx
Content-Type: application/octet-stream

< ./images/celebrities/gutianle-3.jpg
```
However, the same code worked flawlessly last month. I'm pretty sure there's nothing wrong with the server side.

**What I have tired**

I've tried to uninstall this extension,  remove the folder under `~/.vscode/extensions/humao.rest-client-0.21.1` and re-install the latest version (v0.21.1) , but none of them works.

I'm wondering does this extension write  to a temp file? What should I do ?

**Comment by Huachao** [comment] 2019-02-25 03:21
@newbienewbie this is a known issue, and already fixed in #332 , and will publish this fix in next release

**Comment by newbienewbie** [comment] 2019-02-25 04:33
@Huachao  Hi, thanks for your quick response. 

Is there a known date when the next version is released ?

**Comment by Huachao** [comment] 2019-02-25 04:46
@newbienewbie earlier next week or later this week.

**Comment by newbienewbie** [comment] 2019-02-25 04:52
@Huachao Got it . Thanks again for your great extension 💯 !

**Comment by Huachao** [comment] 2019-03-06 13:59
@newbienewbie you can try the latest version to verify

**Comment by newbienewbie** [comment] 2019-03-08 02:55
@Huachao Sorry for the late response. It works now . Thanks 👍
