### ISSUE TITLE
post的时候server无法正常获取body参数

### ISSUE THREAD

**Issue by 477800969** [Huachao/vscode-restclient#78] opened 2017-03-11 16:24 UTC
- VSCode Version:  1.11.0-insider
- OS Version:  x-el 10.11.4
- REST Client Version: 0.12.3

Steps to Reproduce:
1、用扩展运行 
`curl -d "ut=test&uid=123456" "http://localhost/index.php?text=request"`
与
`post http://localhost/index.php?text=request

{
    "ut": "test",
    "uid":"123456"
}`
请求php都获取不到post的body参数，get参数获取成功

2、在shell中跑`curl -d "ut=test&uid=123456" "http://localhost/index.php?text=request"`
可以通过，server端正常获取post参数

**Comment by Huachao** [comment] 2017-03-12 01:33
@477800969 In my test, the request body should be sent to your server, the root cause that your code didn't get this is that you didn't sent the `Content-Type` header  together with the body. So maybe your PHP code will ignore this body.

And in curl shell you can succeed is that, curl in shell automatically adds the `Content-Type` header, while in my extension, no matter which way I won't have this step for you, you should manually and explicitly set the `Content-Type` header.

So you can update the request to following code, I think it can succeed.
```
curl -d "ut=test&uid=123456" "http://localhost/index.php?text=request" --header "Content-Type: application/x-www-form-urlencoded"
```
or
```http
post http://localhost/index.php?text=request
Content-Type: application/json

{
"ut": "test",
"uid":"123456"
}
```

**Comment by 477800969** [comment] 2017-03-12 05:45
Content-Type在测试的时候试过，type的类型都测试了一下，没有效果，还是我使用的姿势不对吗！
index.php的code 很简单
`var_dump($_GET);
var_dump($_POST);
print_r(apache_request_headers());`

**Comment by Huachao** [comment] 2017-03-12 06:12
@477800969 I really don't know the reason why it behaves like this, and I am not familiar with PHP code. The only difference I can found is that using my extension needs you explicitly set request header. And my following `NodeJS` code can work as expected. Could you please double check to add the `Content-Type` header.

```javascript
var http = require('http');

http.createServer((req, res) => {
  var body = "";
  req.on('data', function (chunk) {
    body += chunk;
  });
  req.on('end', function () {
    console.log('POSTed: ' + body);
    res.statusCode = 200;
    res.setHeader('Content-Type', req.headers['content-type']);
    res.end(body);
  });
}).listen(8080);
```

**Comment by 477800969** [comment] 2017-03-12 06:18
![](http://worldheji.com/question.png)
这是我测试的结果

**Comment by 477800969** [comment] 2017-03-12 06:21
看来是php的问题，用node跑了下能过。

**Comment by Huachao** [comment] 2017-03-12 12:00
@477800969 if you don't have more questions, I'd like to close the issue, please feel free to reopen it if you have other concern.

**Closed by Huachao** 2017-03-12 12:00 UTC
Labels: question
