### ISSUE TITLE
Dependencies - testing APIs often needs data from previous API calls

### ISSUE THREAD

**Issue by henrikwh** [Huachao/vscode-restclient#382] opened 2019-06-25 09:00 UTC
It would be useful if you can take dependency on other requests. For testing APIs, this would be very useful.
```
###
# @name postSalesOrder
POST {{cUrl}}/salesOrders?$expand=customer
Authorization: {{authToken}}
Content-Type: application/json

{
    "customerId" : "{{newCustomerId}}"
}
###
@salesOrderId =  {{postSalesOrder.response.body.id}}

###
# @name deleteSalesOrder
DELETE {{cUrl}}/salesOrders({{salesOrderId}})
Authorization: {{authToken}}
Content-Type: application/json
```

In the above, deleteSalesOrder requires salesOrderId as param, which I set by calling postSalesOrder.

Testing a delete request would have a dependency on postSalesOrder, which have the dependencies above.
```
# @name deleteSalesOrder @call postSalesOrder
```

**Comment by Huachao** [comment] 2019-06-25 12:58
Duplicate of #364

**Closed by Huachao** 2019-06-25 12:58 UTC
