### ISSUE TITLE
Windows keybinding with REST extension 

### ISSUE THREAD

**Issue by a8775** [Huachao/vscode-restclient#62] opened 2017-01-18 09:40 UTC
I believe this is more issue with vscode, but as it's related I submit here as well.
The issue in vscode repo: https://github.com/Microsoft/vscode/issues/18712
Thanks a lot for this extension!

Bellow is the inline text of the issue for easy browsing or you find it to be in REST extension.

----
- VSCode Version: 1.9.0-insider (Date 2017-01-18)
- OS Version: Windows 10

Steps to Reproduce:
1. Install REST extension
2. Keybinding is: { "key": "ctrl+alt+e",            "command": "rest-client.switch-environment" },

The problem:
When I press: AltGr+e the command is executed.

Normally I should get special letter that is bonded with national keyboard mapping in Windows.

The issue has possibly two aspects:
1. The command for REST extension should not be executed as it's ctrl+alt+e not alt-e
2. The key binding AltGr+<char> is not differentiated from Alt+<char> - i believe this is related to issue: https://github.com/Microsoft/vscode/issues/17521

**Comment by Huachao** [comment] 2017-01-18 09:50
@a8775 thanks for reporting this, I will keep eyes on this issue, currently I have no idea

**Comment by Huachao** [comment] 2017-04-07 13:01
@a8775 it seems the issue is marked as closed in vscode, so I decide to close it.

**Closed by Huachao** 2017-04-07 13:01 UTC
Labels: upstream
