### ISSUE TITLE
Support #region #endregion for easy requests management in one file

### ISSUE THREAD

**Issue by coolshijun** [Huachao/vscode-restclient#544] opened 2020-03-10 09:48 UTC
It's better to support # region name   ,     # endregion like other languages in VScode. I have many requests in one file, it's easy for me to fold other regions when I focus on just ONE region. Hope it's not that difficult, but really useful.

**Comment by Huachao** [comment] 2020-03-11 07:34
Duplicate of #370

**Closed by Huachao** 2020-03-11 07:34 UTC
