### ISSUE TITLE
Vscode autocomplete not working 

### ISSUE THREAD

**Issue by toplinuxsir** [Huachao/vscode-restclient#76] opened 2017-03-03 02:10 UTC
- VSCode Version: 1.10.1
- OS Version: Debian stretch
- REST Client Version:0.12.3

Steps to Reproduce:

The console output is :

Extension Host] Uncaught Exception:  SyntaxError: Unexpected token s in JSON at position 21935d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] SyntaxError: Unexpected token s in JSON at position 21935
    at fs.readFile (/home/lhs/.vscode/extensions/humao.rest-client-0.12.3/out/src/persistUtility.js:118:42)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:426 Unexpected token s in JSON at position 21935: SyntaxError: Unexpected token s in JSON at position 21935
    at fs.readFile (/home/lhs/.vscode/extensions/humao.rest-client-0.12.3/out/src/persistUtility.js:118:42)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)e.onUnexpectedError @ shell.ts:426(anonymous function) @ shell.ts:383e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by Huachao** [comment] 2017-03-03 02:14
@toplinuxsir I think it should be the `history.json` is corrupted, whose content is used for auto completion, and can you check the file under this path `%USERPROFILE%\.rest-client\history.json`, and update it to make it as a valid JSON, or simply clear the file content.

**Comment by toplinuxsir** [comment] 2017-03-03 02:17
@Huachao  Yes, it works Thanks

**Comment by toplinuxsir** [comment] 2017-03-03 02:22
But is there any way to escape special character such as & 
For Example : 
GET http://10.192.2.239:5000/help/auth_email
   ?email=ttt@sohu.com
   &passwd=pass123&*(

But the backend only receive the param passwd is "pass123" not the whole string "pass123&*("

**Comment by Huachao** [comment] 2017-03-03 02:23
@toplinuxsir got, that's the root cause, I will fix it ASAP

**Comment by Huachao** [comment] 2017-03-03 02:34
@toplinuxsir I think `&` is a special character in query string which is used as a separator, so I can not tell the `&` precisely in query string is the separator or just a normal character. I think you'd better manually escape the & to `%26`.

**Comment by Huachao** [comment] 2017-03-03 11:06
@toplinuxsir I close the issue now, please feel free to reopen it.

**Closed by Huachao** 2017-03-03 11:06 UTC
Labels: bug, question
