### ISSUE TITLE
I can't copy the contents in the split editor. 

### ISSUE THREAD

**Issue by MyWorldG** [Huachao/vscode-restclient#657] opened 2020-08-07 00:10 UTC
Issue Type: <b>Bug</b>

I can't copy and paste content in the editor window of the response

Extension version: 0.24.1
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (8.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by MyWorldG** [comment] 2020-08-07 00:10
![vscodebug3](https://user-images.githubusercontent.com/53108767/89594802-6bdb3700-d885-11ea-8b7e-c96ee0039aae.gif)

**Comment by LennardFi** [comment] 2020-08-07 06:50
Same in my vscode

Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Extension-Version: v0.24.1

**Comment by MyWorldG** [comment] 2020-08-08 03:38
@Huachao

**Comment by Huachao** [comment] 2020-08-11 05:30
Duplicate of #641

**Closed by Huachao** 2020-08-11 05:30 UTC
