### ISSUE TITLE
Split the executor out into a console app

### ISSUE THREAD

**Issue by kbirger** [Huachao/vscode-restclient#759] opened 2021-01-29 18:25 UTC
Someone introduced me to this extension today. Looks awesome! One thing that I think would deliver huge value would be to split the code up so that the execution can be triggered via a commandline app.

Basically, we are considering scripting some examples for a service we are developing and storing them alongside our codebase. It would be really great if we could wire up part of our CI process to test the snippets we generate to make sure they still behave correctly.

```bash
restclient foo.http
```

**Comment by thegruffalo** [comment] 2021-02-07 17:28
#432 is a similar request. I wonder if some of the comments in there may give you a way forward - idea cli runner.

**Comment by Huachao** [comment] 2021-02-09 08:27
Duplicate of #759

**Closed by Huachao** 2021-02-09 08:27 UTC

**Comment by dremekie** [comment] 2021-02-19 16:08
@Huachao  You closed this but called it a duplicate of itself.  Did you mean this is a duplicate of #750 ?
