### ISSUE TITLE
Lazy evaluated variables

### ISSUE THREAD

**Issue by rafek1241** [Huachao/vscode-restclient#670] opened 2020-08-27 18:37 UTC
I would like to see something like a postman client.
Example:
```
###

# @name getAsset
# Retrieve an asset by its ID
GET /api/v1/projects/{{project}}/assets/:id
api-key: {{api-key}}
```
Expected result:

When `SendRequest` will be clicked then there will be prompt to write the remaining id. We won't need to specify it before request execution but during the process.

Possible addition:
```
###
# @name getAsset
# @param:id Id of the asset that you want to see
# Retrieve an asset by its ID
GET /api/v1/projects/{{project}}/assets/:id
api-key: {{api-key}}
```
Explanation:
in the line `# @param:id` we would define the description message of the prompted variable to hint user what he/she should put there.

**Comment by Huachao** [comment] 2020-08-28 09:42
Duplicate of #479

**Closed by Huachao** 2020-08-28 09:42 UTC
