### ISSUE TITLE
Variable from body of response for next request causes 400 bad request

### ISSUE THREAD

**Issue by avlasics** [Huachao/vscode-restclient#615] opened 2020-06-17 19:29 UTC
- REST Client Version: 0.24.1
- VSCode Version: 1.46.0
- OS Version: Windows 10

**Steps to Reproduce:**

Request:
```
###
# @name auth
POST http://localhost:5000/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

grant_type=client_credentials&scope=Link.Pos.Api&client_id=pos-client2&client_secret=D***1

@token = {{auth.response.body.$.access_token}}
```

Response:
400 error - bad request

**Workaround:**

- Revert to version 0.23.2
- Remove @token variable

Response:
```
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache, max-age=0
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8
Server: 
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Date: Wed, 17 Jun 2020 19:07:19 GMT
Connection: close

{
  "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjJGODVFQzJEOTBENjUxNDc0RTlFRUExRkFGNTdDQjU1RkVERjIyMEYiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJMNFhzTFpEV1VVZE9udW9mcjFmTFZmN2ZJZzgifQ.eyJuYmYiOjE1OTI0MjA4MzksImV4cCI6MTU5MjQyNDQzOSwiaXNzIjoiaHR0cHM6Ly9uZXdtZXhpY29icm9rZXIucWEudGVzdC9pZGVudGl0eSIsImF1ZCI6IkxpbmsuUG9zLkFwaSIsImNsaWVudF9pZCI6InZlbG9jaXR5LXFhIiwiY2xpZW50X3Bvc0FsdCI6IlZFTE9DSVRZIiwiY2xpZW50X2ludGVyZmFjZV90eXBlIjoiMzIiLCJjbGllbnRfaW50ZXJmYWNlX2NvZGUiOiI0MCIsImNsaWVudF9pbnRlcmZhY2Vfc3ViY29kZSI6ImlzNCIsImNsaWVudF9wb3NTeXN0ZW0iOlsiRExDLlZFTE9DSVRZIiwiT3R0byJdLCJzY29wZSI6WyJMaW5rLlBvcy5BcGkiXX0.py4WzUHhlX3H-QXeNsuU34GYSsgrxK1vmvU4urMrwC0YPYA6g3urHkYTsI6J3fsr3Gkmu1Rtu4_bYAhNlS9rvT4-cB0CD5044hGGt7p58v_t6tWIxxBFI23L_jCeBK1ZMAEjyILU5_K5mxVbH4MhPGo6EsiikdHThKdnqTZ18hU0o2MZ1FJ3jlyDyZiehnC33bhYDO_Oln6iHzd58iZZL42bHPnSoGg8xm4Fgg03B7BGqnbzSEoo1j21SQ2oF5b8Mnccfx9MyaLUi72Qxec1oEq9jCrlTy6hPPhrOjuIrs2aDm-whW5E-nBEq98MQ13FD13DBEqgMHuY1kPmJb97pA",
  "expires_in": 3600,
  "token_type": "Bearer",
  "scope": "Link.Pos.Api"
}
```

**Comment by Huachao** [comment] 2020-06-18 01:26
Duplicate of #607

**Comment by Huachao** [comment] 2020-06-18 01:27
@avlasics as described here https://github.com/Huachao/vscode-restclient/issues/607#issuecomment-643340438, you need to put the request block delimiter `###` before the file variables declaration.

**Closed by Huachao** 2020-06-18 01:27 UTC
