### ISSUE TITLE
Cannot copy data from response

### ISSUE THREAD

**Issue by codermrrob** [Huachao/vscode-restclient#641] opened 2020-07-17 07:49 UTC
- REST Client Version: 0.24.1
- VSCode Version: 1.47.2
- OS Version: Win_NT x64 10.0.18362

Steps to Reproduce:

Sorry I know this is vague, but its hard to make it repeatable. Some responses seem to have become impossible to copy data from. Others still are fine. 

I can repeat it with bearer tokens, from an authorization endpoint, from one API every time.

Make the auth request, tokens are returned to the response editor (as exepected). But if I select the token (or any part of it) in the response and hit CTRL-C and attempt to paste it into my working editor all I get is an empty line. Also this used to work fine, I've been doing this for a couple of years with your plugin, which is awesome by the way.

As a feature suggestion it would be really convenient to have the response as a normal editor window, or at least an option for that.

**Comment by CharlieScarver** [comment] 2020-07-18 02:20
- REST Client 0.24.1
- VS Code 1.47.2
- OS Windows_NT x64 10.0.19041

Can't use Ctrl+C in the Result tab anymore.
It was working until earlier today, when I restarted VS Code. 

I updated both my REST Client and my VS Code (from 1.30...) today so maybe one of those has something to do with it.

More details:
The behavior is not that straightforward. If you select the full body of the request you can copy. Also if you select 6 or more rows from the BODY you can copy. But if you select lines only from the headers or less than 6 from the body you can't copy. Very odd.
(And annoying.)

**Comment by Huachao** [comment] 2020-07-18 15:28
> As a feature suggestion it would be really convenient to have the response as a normal editor window, or at least an option for that.

Normal document view is supported by set the setting `rest-client.previewResponseInUntitledDocument` to `true`

**Comment by Huachao** [comment] 2020-07-18 15:34
@CharlieScarver @codermrrob this seems to be related with the VS Code update in 1.47.2, issues already reported by others in the VS Code repository microsoft/vscode#102736

**Comment by codermrrob** [comment] 2020-07-21 06:51
Thanks - just switching views in the response. Can't believe I missed that :/

Thanks again, great tool, its so much more convenient than Postman, etc

**Comment by matiasg77** [comment] 2020-07-22 15:41
Same problem!
vscode version: 1.47.2

**Comment by Huachao** [comment] 2020-07-24 01:26
@CharlieScarver @matiasg77 @codermrrob @DonatasBrazionis @stanb-quali @Hawken94 @ytrinh @rodolphocastro According to the microsoft/vscode#102736, it has been fixed in the latest insider build, could you please confirm it is available. Thanks in advance.

**Closed by Huachao** 2020-07-24 01:26 UTC
Labels: upstream

**Comment by rodolphocastro** [comment] 2020-07-24 11:37
> [...] According to the [microsoft/vscode#102736](https://github.com/microsoft/vscode/issues/102736), it has been fixed in the latest insider build, could you please confirm it is available. Thanks in advance.

I can confirm it's working like a charm on Insiders:

![hsZ76IX07y](https://user-images.githubusercontent.com/2666310/88387424-c86c2b80-cd88-11ea-85b8-6c9c4ea322e0.gif)

**Comment by Joeboyc2** [comment] 2020-08-13 13:09
> @CharlieScarver @codermrrob this seems to be related with the VS Code update in 1.47.2, issues already reported by others in the VS Code repository [microsoft/vscode#102736](https://github.com/microsoft/vscode/issues/102736)

This change has fixed the issues for me, thank you @Huachao it was really bugging me
