### ISSUE TITLE
Parse response variables from non-standard Content-Type

### ISSUE THREAD

**Issue by martinschayna** [Huachao/vscode-restclient#604] opened 2020-06-11 15:09 UTC
I have to work against a bit non standard API, which produces response with Content-Type:
```
Content-Type: text/javascript; charset=utf-8
```
but in fact the response body is pretty normal JSON format. In this case I cannot use parsing response variables in subsequent requests just like `{{nameOfRequest.response.body.$.id}}` because of warning:

```
Only JSON and XML response/request body is supported to query the result`.
```

I thought that the parameter `suppressResponseBodyContentTypeValidationWarning: true` is there for it, but it doesn't work either.

It would be nice to have settings for default content type in case of unknown or maybe mapping from non-standard content types to standard ones.

Thanks a lot and keep up this wonderful work!

**Comment by Huachao** [comment] 2020-06-12 01:18
Duplicate of #327

**Closed by Huachao** 2020-06-12 01:18 UTC
