### ISSUE TITLE
ability to grab the token from response header and set it as a variable to use in next call

### ISSUE THREAD

**Issue by cilerler** [Huachao/vscode-restclient#136] opened 2017-11-09 16:11 UTC
- VSCode Version: 1.18
- OS Version: 
- REST Client Version: 0.16

# Steps to Reproduce:

HTTP file

```
@host = <MYAPIURL>
@token = <MYEMPTYVALUE>

### Login
POST /api/Authenticate/Login HTTP/1.1
Host: {{host}}
Content-Type: application/json
Cache-Control: no-cache

{
    "username":"<MYUSERNAME>",
    "password":"<MYPASSWORD>"
}

### UserDetails
GET /api/Authenticate/UserDetails HTTP/1.1
Host: {{host}}
Authorization: bearer {{token}}
Cache-Control: no-cache
```

When I send request for _Login_ it will return result below

```
HTTP/1.1 200 OK
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
Token: ewdweefwefhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiNTZiNGY5YmNhM2RmMDIwOTAwNjU5NzI5IiwiaWF0IjoxNTEwMjQzNDwefwefwefDcwOTksImlzcyI6ImFwaS5zbWFydHByb2N1cwefwefwefaCrMk2sQ9DKPKRHIffazYfijZ2jwhpqxxmywCuUM
Date: Thu, 09 Nov 2017 16:04:59 GMT
```

I would like to be able to grab the `Token` from that response and replace it as local environment `@token` with it.

So when I send request for _UserDetails_ it should send the request with the token I received and not with the *MYEMPTYVALUE*

**Comment by Huachao** [comment] 2017-11-10 02:06
@cilerler really nice suggestion, and some issues like #86 is already related to this, so I'd like to close this to in favor of that one. And any updates will be recorded in that thread.

Duplicate of #86

**Closed by Huachao** 2017-11-10 02:06 UTC
