### ISSUE TITLE
Is there any support for locally (per request) scoped variables?

### ISSUE THREAD

**Issue by Jaimeloeuf** [Huachao/vscode-restclient#642] opened 2020-07-20 17:44 UTC
I looked into using variables for defining APIs and find it extremely useful and important to developer workflows. However upon closer inspection of <https://github.com/Huachao/vscode-restclient#file-variables>, I realise that all variables are globally scoped or scoped to the entire file, regardless of its location of definition.

Is there anyway to define locally scoped variables for individual requests?

For example:
```
### Get a user's plan
@userID = 1 // Where this is scoped in between the 2 parent "###" symbols rather then the whole file

GET {{host}}/subscription/:userID

### 
```

This is useful and helps to increase productivity of developers, as we can see the whole URL in a single glance, so that we know exactly what route this is, rather than having to see something like that below and mentally translate it

```
### Get a user's plan
GET {{host}}/subscription/1 // Where 1 is the userID

### 
```

I think this is a great extension, and many users probably migrated here from postman like myself, and this is one of the small but very convenient feature of postman, that will be missed. Below is a SS from postman to show how it looks like:
![image](https://user-images.githubusercontent.com/44993072/87969495-d4d85600-caf4-11ea-96f2-42f74ff60b52.png)

As can be seen from the picture, it makes it easy to read and clear to define what are the variables and its values, and also allows us to include in descriptions which can help to facilitate communications and better documentations in teams!

I'm not fully sure what this extra feature will entail for the project, but if this is possible, I would be able to volunteer my time to help and implement this!

**Comment by Huachao** [comment] 2021-12-04 16:49
Duplicate of #414

**Comment by Huachao** [comment] 2021-12-04 16:49
@Jaimeloeuf close this to in favor of the original one

**Closed by Huachao** 2021-12-04 16:49 UTC
Labels: feature request
