### ISSUE TITLE
Explorer UI for .rest/.http files

### ISSUE THREAD

**Issue by OysteinAmundsen** [Huachao/vscode-restclient#401] opened 2019-08-04 14:38 UTC
Hi.

This extension is great. The option to store requests as a way to document api's right inside the source folder for my api is fantastic. But what would be even more fantastic, is if there was a UI explorer available to browse all my *.rest files - like the `Test Explorer UI`. 

For me, this feature would make tools like "Postman" or "Insomnia" completely redundant.

**Comment by Huachao** [comment] 2019-11-25 04:56
Duplicate of #360

**Closed by Huachao** 2019-11-25 04:56 UTC
Labels: feature request
