### ISSUE TITLE
Support for API documentation.

### ISSUE THREAD

**Issue by SutharMukesh** [Huachao/vscode-restclient#618] opened 2020-06-21 09:37 UTC
The extension works great when creating REST calls and maintaining them in `.http` files, I can also specify a description for an API inside a comment but there is no sperate support for documenting all APIs.  
> I liked how _postman_ creates the API document for us.  

Is there any way I can export the `.http` file into postman collection format? as I can generate docs inside postman.  
or can the extension have swagger like API docs support?

**Comment by Huachao** [comment] 2020-06-22 01:36
Duplicate of #67

**Closed by Huachao** 2020-06-22 01:36 UTC

**Comment by verydemo** [comment] 2023-03-16 05:56
up up up
