### ISSUE TITLE
[Feature] Import variables from another file

### ISSUE THREAD

**Issue by xdmushui** [Huachao/vscode-restclient#447] opened 2019-11-20 04:38 UTC
Maybe put variables to file.
For example:

```
// file: variables.http 

@base_url = https://localhost:44366
@client_id = abc-abc-abc
@client_secret = 1q2w3e4r5t6y7u

// @name getTokenApi
POST {{base_url}}/oauth2/token
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept: */*
Accept-Encoding: gzip, deflate

?client_id={{client_id}}
&client_secret={{client_secret}}

// get token from response
@access_token = {{getTokenApi.response.body.access_token}}
@refresh_token = {{getTokenApi.response.body.refresh_token}}
````
After executing getTokenApi in variables.http,
The @access_token variable will have a value. In another file (test-myapp.http), you can use this variable:
```
// file: test-myapp.http

{{ $import variables.http }}

@customer_id = 1234

// @name getCustomerInfo
GET {{base_url}}/v1/customers/{{customer_id}}
Authorization: Bearer {{access_token}}

```

I think this might help us.

**Comment by Huachao** [comment] 2019-11-25 04:54
Duplicate of #182

**Closed by Huachao** 2019-11-25 04:54 UTC
