### ISSUE TITLE
 But all styles including: background color, foreground color, buttons, borders, s...

### ISSUE THREAD

**Issue by zhouxinghong** [Huachao/vscode-restclient#1151] opened 2023-05-10 03:57 UTC
This extension is awesome! 👍👍👍 But all styles including: background color, foreground color, buttons, borders, scroll bars, input boxes, etc. should inherit from theme styles instead of another set of styles. . . Only in this way can it be consistent with the theme style. . . Better user experience! 😜😜
Windows10
0.25.1

**Comment by Huachao** [comment] 2023-07-06 16:09
Duplicate of #1150

**Closed by Huachao** 2023-07-06 16:09 UTC
